from __future__ import annotations

import argparse
import json
from pathlib import Path

import cv2
import numpy as np


COLORS = {
    "Right": (0, 210, 255),
    "Left": (80, 255, 80),
    "Unknown": (220, 220, 220),
}


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Render a COCO-style hand keypoint JSON as a black-background skeleton video.")
    parser.add_argument("json_path", type=Path, help="COCO-style JSON generated by extract_clip_keypoints.py.")
    parser.add_argument("-o", "--output", type=Path, default=None, help="Output video path. Default: <json_stem>_skeleton.mp4")
    parser.add_argument("--fps", type=float, default=None, help="Override output FPS.")
    parser.add_argument("--hand", choices=["Right", "Left", "Both"], default="Both")
    return parser.parse_args()


def annotation_points(annotation: dict) -> list[tuple[int, int, int]]:
    values = annotation["keypoints"]
    points = []
    for index in range(0, len(values), 3):
        points.append((int(round(values[index])), int(round(values[index + 1])), int(values[index + 2])))
    return points


def draw_annotation(frame, annotation: dict, skeleton: list[list[int]]) -> None:
    hand = annotation.get("handedness") or "Unknown"
    color = COLORS.get(hand, COLORS["Unknown"])
    points = annotation_points(annotation)
    line_color = (120, 120, 120) if annotation.get("interpolated") else color

    for start, end in skeleton:
        a = points[start - 1]
        b = points[end - 1]
        if a[2] > 0 and b[2] > 0:
            cv2.line(frame, (a[0], a[1]), (b[0], b[1]), line_color, 2, cv2.LINE_AA)

    for x, y, visible in points:
        if visible > 0:
            cv2.circle(frame, (x, y), 3, color, -1, cv2.LINE_AA)


def main() -> int:
    args = parse_args()
    json_path = args.json_path.resolve()
    data = json.loads(json_path.read_text(encoding="utf-8"))
    output_path = args.output.resolve() if args.output else json_path.with_name(f"{json_path.stem}_skeleton.mp4")

    info = data.get("info", {})
    width = int(info.get("width") or 1280)
    height = int(info.get("height") or 720)
    fps = float(args.fps or info.get("sample_fps") or info.get("fps") or 30)
    if fps <= 0 or fps > 120:
        fps = 30

    categories = {category["id"]: category for category in data.get("categories", [])}
    skeleton = categories.get(1, {}).get("skeleton", [])
    annotations_by_image: dict[int, list[dict]] = {}
    for annotation in data.get("annotations", []):
        hand = annotation.get("handedness") or "Unknown"
        if args.hand != "Both" and hand != args.hand:
            continue
        annotations_by_image.setdefault(annotation["image_id"], []).append(annotation)

    output_path.parent.mkdir(parents=True, exist_ok=True)
    writer = cv2.VideoWriter(str(output_path), cv2.VideoWriter_fourcc(*"mp4v"), fps, (width, height))
    if not writer.isOpened():
        raise RuntimeError(f"Could not open video writer: {output_path}")

    for image in sorted(data.get("images", []), key=lambda item: item["id"]):
        frame = np.zeros((height, width, 3), dtype=np.uint8)
        for annotation in annotations_by_image.get(image["id"], []):
            draw_annotation(frame, annotation, skeleton)
        cv2.putText(
            frame,
            f"frame {image.get('frame_index', image['id'])}  t={image.get('time', 0):.2f}s",
            (18, 34),
            cv2.FONT_HERSHEY_SIMPLEX,
            0.8,
            (210, 210, 210),
            2,
            cv2.LINE_AA,
        )
        writer.write(frame)

    writer.release()
    print(output_path)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
